FIX compil test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -50,28 +50,28 @@ jobs:
             echo No unwanted files detected
           fi
 
-check_program_compilation:
-  needs: [check_repo]
-  name: "Checks if make compil and test all binary listed in the ARGUMENTS variable"
-  runs-on: ubuntu-latest
-  container:
-    image: epitechcontent/epitest-docker:latest
-  steps:
-    - uses: actions/checkout@v4
-    - name: Check for Makefile and compile
-      run: |
-        if [ -f Makefile ]; then
-          for target in all clean fclean re; do
-            make $target
-            if [ $? -ne 0 ]; then
-              echo "Error: make $target failed with exit code $make_exit_code"
-              exit 1
-            fi
-          done
-        else
-          echo "Makefile not found, skipping compilation and testing."
-        fi
-      timeout-minutes: 5
+  check_program_compilation:
+    needs: [check_repo]
+    name: "Checks if make compil and test all binary listed in the ARGUMENTS variable"
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check for Makefile and compile
+        run: |
+          if [ -f Makefile ]; then
+            for target in all clean fclean re; do
+              make $target
+              if [ $? -ne 0 ]; then
+                echo "Error: make $target failed with exit code $make_exit_code"
+                exit 1
+              fi
+            done
+          else
+            echo "Makefile not found, skipping compilation and testing."
+          fi
+        timeout-minutes: 5
 
 
   run_tests:
