FIX criterion tests

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -63,8 +63,8 @@ jobs:
           if [ -f Makefile ]; then
             for target in all clean fclean re; do
               make $target
-              if [ $? -ne 0 ]; then
-                echo "Error: make $target failed with exit code $make_exit_code"
+              if [ make_exit_code -ne 0 ]; then
+                echo "Error: make $target failed with exit code $?"
                 exit 1
               fi
             done
@@ -73,28 +73,32 @@ jobs:
           fi
         timeout-minutes: 5
 
+run_tests:
+  needs: [check_program_compilation]
+  name: "Runs tests with criterion"
+  runs-on: ubuntu-latest
+  container:
+    image: epitechcontent/epitest-docker:latest
 
-  run_tests:
-    needs: [check_program_compilation]
-    name: "Runs tests with criterion"
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker:latest
-
-    steps:
-      - uses: actions/checkout@v4
-      - id: run_tests
-        run: |
-          if [ -f Makefile ]; then
-            make tests_run
-            if [ $? -ne 0 ]; then
-              echo "Error: make tests_run failed with exit code $make_exit_code"
-              exit 1
-            fi
+  steps:
+    - uses: actions/checkout@v4
+    - name: Run tests if rule exists
+      run: |
+        if [ -f Makefile ]; then
+          make tests_run
+          make_exit_code=$?
+          if [ $make_exit_code -eq 0 ]; then
+            echo "Tests run successfully"
+          elif [ $make_exit_code -eq 2 ]; then
+            echo "Test rule not found, skipping tests."
           else
-            echo "Makefile not found, skipping tests."
+            echo "Error: make tests_run failed with exit code $make_exit_code"
+            exit 1
           fi
-        timeout-minutes: 2
+        else
+          echo "Makefile not found, skipping tests."
+        fi
+      timeout-minutes: 2
 
   push_to_mirror:
     needs: [check_coding_style, run_tests, check_repo, check_program_compilation]
