FIX 'cstyle' of the testing C file

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -26,6 +26,7 @@ jobs:
           done
           if [[ -n $CODING_STYLE_ERRORS ]]
           then
+            echo "$
             exit 1
           else
             echo No coding style errors detected
@@ -82,18 +83,19 @@ jobs:
   
     steps:
       - uses: actions/checkout@v4
-      - name: Run tests if rule exists
+      - name: Check if tests_run rule exists
         run: |
           if [ -f Makefile ]; then
-            make tests_run
-            make_exit_code=$?
-            if [ $make_exit_code -eq 0 ]; then
-              echo "Tests run successfully"
-            elif [ $make_exit_code -eq 2 ]; then
-              echo "Test rule not found, skipping tests."
+            if cat Makefile | grep -q "tests_run"; then
+              make tests_run
+              if [ $? -eq 0 ]; then
+                echo "Tests run successfully"
+              else
+                echo "Error: make tests_run failed"
+                exit 1
+              fi
             else
-              echo "Error: make tests_run failed with exit code $make_exit_code"
-              exit 1
+              echo "tests_run rule not found, skipping tests."
             fi
           else
             echo "Makefile not found, skipping tests."
